services:
  development:
    #     # userns_mode: "keep-id"
    build:
      context: .
      target: development
      args:
        UID: ${UID}
        GID: ${GID}
    volumes:
      - ./:/home/backend/project
    environment:
      - NODE_ENV=development
      - DATABASE_URL=postgresql://user:pass@host:5432/mydb
    ports:
      - '2280:22'
      - '8000:8000'
    profiles:
      - development
#   production:
#     # userns_mode: "keep-id"
#     build:
#       context: .
#       target: production
#       args:
#         UID: ${UID}
#         GID: ${GID}
#     environment:
#       - NODE_ENV=production
#     ports:
#       - '8000:8000'
#     profiles:
#       - production
