services:
  development:
    # userns_mode: "keep-id"
    build:
      context: .
      target: development
      args:
        UID: ${UID}
        GID: ${GID}
    volumes:
      - ./:/home/user/backend
    environment:
      - DATABASE_URL=postgresql://user:pass@host:5432/mydb
    ports:
      - '8000:8000'
      - '58000:58000'
    profiles:
      - development

  production:
    # userns_mode: 'keep-id'
    build:
      context: .
      target: production
    environment:
      - DATABASE_URL=postgresql://user:pass@host:5432/mydb
    ports:
      - '8000:8000'
    profiles:
      - production
