services:
  backend:
    build:
      context: ..
      target: production
      dockerfile: docker/image/dockerfile
    platform: linux/amd64
    environment:
      - DATABASE_URL=${DATABASE_URL}
    ports:
      - '8000:8000'
    restart: unless-stopped
    depends_on:
      - postgres

  postgres:
    image: postgres:17-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  postgres_data: