services:
  backend:
    build:
      context: ..
      target: production
      dockerfile: docker/Dockerfile
    environment:
      - DATABASE_URL=${DATABASE_URL}
    ports:
      - '8000:8000'
    restart: unless-stopped
